### ISSUE TITLE
Autodetect AWS-cli and other dependencies 

### ISSUE THREAD

**Issue by jpablomch** [jblakley/ScannerEKSQS#30]
Ideally, the user should wget only one script that configures the staging machine. 

The main script should detect whether aws-cli and other dependencies have been installed (currently handled by awscli_setup.sh). The main script should also detect whether the vpc has been created (create_vpc.sh). 

We should try to reduce the number of additional scripts that the user has to wget and keep things as simple as possible.

**Comment by jblakley** [comment]
@jpablomch  -- Agree on the awscli script and baseline_*.sh does install it. The problem with vpc was a bootstrapping problem:

1. The staging machine has to be in the same vpc as the cluster.
2. But, you can't move an instance from one vpc to another. 
3. So, you have to create the vpc and then create a staging machine in that vpc.
4.  You can run create_vpc.sh from any machine with aws cli access. 
5. We should add a check for awscli in create_vpc.sh and install it if not.
6. But, it doesn't make sense to put create_vpc.sh into baseline_*.sh.

**Comment by jblakley** [comment]
I've added a conditional install of awscli in create_eks.sh and cleaned up the README
